default_profile: master
profiles:
  local:
    host: localhost:8001
    org: example.org
    token: ""
  master:
    host: https://us-master.gladly.qa
    org: gladly.com
    token: ""
  production:
    host: https://us-1.gladly.com
    org: gladly.com
    token: ""
  staging:
    host: https://us-staging.gladly.qa
    org: gladly.com
    token: ""
  uat:
    host: https://us-uat.gladly.qa
    org: gladly.com
    token: ""
